[package]
name = "resource"
version = "0.1.0"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2018"
license = "Apache-2.0"

[dev-dependencies]
test-utils = { path = "../../../libs/test-utils" }
tempfile = "3.2.0"

[dependencies]
anyhow = "^1.0"
actix-rt = "2.7.0"
async-trait = "0.1.48"
bitflags = "1.2.1"
byte-unit = "4.0.14"
cgroups-rs = "0.3.2"
futures = "0.3.11"
lazy_static = "1.4.0"
libc = ">=0.2.39"
netns-rs = "0.1.0"
netlink-sys = "0.8.3"
netlink-packet-route = "0.13.0"
nix = "0.24.2"
rand = "^0.7.2"
rtnetlink = "0.11.0"
scopeguard = "1.0.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
slog = "2.5.2"
slog-scope = "4.4.0"
tokio = { version = "1.38.0", features = ["process"] }
tracing = "0.1.36"
uuid = { version = "0.4", features = ["v4"] }

agent = { path = "../agent" }
hypervisor = { path = "../hypervisor" }
kata-types = { path = "../../../libs/kata-types" }
kata-sys-util = { path = "../../../libs/kata-sys-util" }
logging = { path = "../../../libs/logging" }
oci-spec = { version = "0.6.8", features = ["runtime"] }
persist = { path = "../persist"}
tests_utils = { path = "../../tests/utils" }

[features]
