apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kata-annotation-webhook
  labels:
    app: kata-annotation-webhook
    kind: mutator
webhooks:
  - name: webhook.kata.dev
    clientConfig:
      service:
        name: kata-annotation-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: <CA_BUNDLE>
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
