apiVersion: apps/v1
kind: Deployment
metadata:
  name: kata-annotation-webhook
  labels:
    app: kata-annotation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kata-annotation-webhook
  template:
    metadata:
      labels:
        app: kata-annotation-webhook
    spec:
      containers:
        - name: kata-annotation-webhook
          image: quay.io/kata-containers/kata-annotation-webhook:latest
          imagePullPolicy: Always
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: kata-annotation-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: kata-annotation-webhook-svc
  labels:
    app: kata-annotation-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: kata-annotation-webhook