[[constraint]]
  name = "github.com/clearcontainers/proxy"
  revision = "1d2a6a3ea132a86abd0731408b7dc34f2fc17d55"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  revision = "7f98c94613021d8b57acfa1a2f0c8d0f6fd7ae5a"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "20b96f641a5ea98f2f8619ff4f3e061cff4833bd"

[[constraint]]
  name = "github.com/kubernetes-incubator/cri-o"
  revision = "3394b3b2d6af0e41d185bb695c6378be5dd4d61d"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "d0303fe809921458f417bcf828397a65db30a7e4"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "0351df1c5a66838d0c392b4ac4cf9450de844e2d"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "5806c35637336642129d03657419829569abc5aa"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "890a5c3458b43e6104ff5da8dfa139d013d77544"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "ac249472b7de27a9e8990819566d9be95ab5b816"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "c2a3de3b38bd00f07290c3c5e12b4dbc04ec8666"

[[constraint]]
  name = "github.com/vishvananda/netns"
  revision = "86bef332bfc3b59b7624a600bd53009ce91a9829"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "1d2aa6dbdea45adaaebb9905d0666e4537563829"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"

[[constraint]]
  name = "github.com/intel/govmm"
  revision = "78d079db6d1f3e32e3ed7578a54baa6257b058a7"

[[constraint]]
  name = "github.com/kata-containers/agent"
  revision = "8e48125fa2a793706e5e660e95bdc9755f1cf474"

[[constraint]]
  name = "github.com/containerd/cri-containerd"
  revision = "4dd6735020f5596dd41738f8c4f5cb07fa804c5e"

[[constraint]]
  name = "github.com/safchain/ethtool"
  revision = "79559b488d8848b53a8e34c330140c3fc37ee246"

[[constraint]]
 name = "github.com/containerd/containerd"
 revision = "f05672357f56f26751a521175c5a96fc21fa8603"

[[constraint]]
  name = "github.com/firecracker-microvm/firecracker-go-sdk"
  revision = "961461227bddf7e40a1d690634e866c343910f86"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "342cbe0a04158f6dcb03ca0079991a51a4248c02"

[[override]]
  branch = "master"
  name = "github.com/hashicorp/yamux"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  revision = "5017d4e9a9cf2d4381db99eacd9baf84b95bfb14"
  name = "github.com/containerd/cgroups"
