[[constraint]]
  name = "github.com/containernetworking/plugins"
  revision = "485be65581341430f9106a194a98f0f2412245fb"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "20b96f641a5ea98f2f8619ff4f3e061cff4833bd"

[[constraint]]
  name = "github.com/cri-o/cri-o"
  revision = "3394b3b2d6af0e41d185bb695c6378be5dd4d61d"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "d0303fe809921458f417bcf828397a65db30a7e4"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "2b52db75279ca687e18156de86d845876e9ef35d"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "a1b50f621a48ad13f8f696a162f684a241307db0"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "890a5c3458b43e6104ff5da8dfa139d013d77544"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "ac249472b7de27a9e8990819566d9be95ab5b816"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "c8c507c80ea28385caac72b682dd066e44943913"

[[constraint]]
  name = "github.com/vishvananda/netns"
  revision = "86bef332bfc3b59b7624a600bd53009ce91a9829"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "b016eb3dc98ea7f69ed55e8216b87187067ae621"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "v1.4.2"

[[constraint]]
  name = "github.com/intel/govmm"
  revision = "e969afbec52cf687bbe97b76654c664128cdb04b"

[[constraint]]
  name = "github.com/kata-containers/agent"
  revision = "d26a505efd336e966636f9aa30eaacd29cf8a58f"

[[constraint]]
  name = "github.com/containerd/cri-containerd"
  revision = "4dd6735020f5596dd41738f8c4f5cb07fa804c5e"

[[constraint]]
  name = "github.com/safchain/ethtool"
  revision = "79559b488d8848b53a8e34c330140c3fc37ee246"

[[constraint]]
 name = "github.com/containerd/containerd"
 revision = "f05672357f56f26751a521175c5a96fc21fa8603"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "4cbf7e384e768b4e01799441fdf2a706a5635ae7"

[[override]]
  name = "github.com/containerd/ttrpc"
  revision = "92c8520ef9f86600c650dd540266a007bf03670f"

[[override]]
  branch = "master"
  name = "github.com/hashicorp/yamux"

[[constraint]]
  revision = "0650fd9eeb50bab4fc99dceb9f2e14cf58f36e7f"
  name = "github.com/containerd/console"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  revision = "c4b9ac5c7601384c965b9646fc515884e091ebb9"
  name = "github.com/containerd/cgroups"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/procfs"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.1"

[[constraint]]
  name = "github.com/opencontainers/selinux"
  version = "1.3.3"
