# This is an agent configuration file example.
dev_mode = true
server_addr = 'vsock://8:2048'

[endpoints]
# All endpoints are allowed
allowed = [
        "AddARPNeighborsRequest",
        "AddSwapRequest",
        "CloseStdinRequest",
        "CopyFileRequest",
        "CreateContainerRequest",
        "CreateSandboxRequest",
        "DestroySandboxRequest",
        "ExecProcessRequest",
        "GetMetricsRequest",
        "GetOOMEventRequest",
        "GuestDetailsRequest",
        "ListInterfacesRequest",
        "ListRoutesRequest",
        "MemHotplugByProbeRequest",
        "OnlineCPUMemRequest",
        "PauseContainerRequest",
        "PullImageRequest",
        "ReadStreamRequest",
        "RemoveContainerRequest",
        "ReseedRandomDevRequest",
        "ResumeContainerRequest",
        "SetGuestDateTimeRequest",
        "SignalProcessRequest",
        "StartContainerRequest",
        "StartTracingRequest",
        "StatsContainerRequest",
        "StopTracingRequest",
        "TtyWinResizeRequest",
        "UpdateContainerRequest",
        "UpdateInterfaceRequest",
        "UpdateRoutesRequest",
        "WaitProcessRequest",
        "WriteStreamRequest"
]
