[package]
name = "shim-ctl"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = [ "rt", "rt-multi-thread" ] }

# Local dependencies
common = { workspace = true }
logging = { workspace = true }
runtimes = { workspace = true }
