# Copyright (c) 2024 Microsoft Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[package]
name = "genpolicy"
version = "0.1.0"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
# Logging.
env_logger = "0.10.0"
log = "0.4.17"

# Command line parsing.
clap = { version = "4.1.8", features = ["derive"] }

# YAML file serialization/deserialization.
base64 = "0.21.0"
serde = { version = "1.0.159", features = ["derive"] }

# Newer serde_yaml versions are using unsafe-libyaml instead of yaml-rust,
# and incorrectly change on serialization:
#
# value: "yes"
#
# to:
#
# value: yes
#
# In YAML, the value yes without quotes is reserved for boolean,
# and confuses kubectl, that expects a string value.
serde_yaml = "0.8"

# Container repository.
anyhow = "1.0.32"
async-trait = "0.1.68"
docker_credential = "1.3.1"
flate2 = { version = "1.0.26", features = ["zlib-ng"], default-features = false }
libz-ng-sys = "1.1.15" # force newer version that compiles on ppc64le
oci-distribution = { version = "0.10.0" }
openssl = { version = "0.10.54", features = ["vendored"] }
serde_ignored = "0.1.7"
serde_json = "1.0.39"
serde-transcode = "1.1.1"
tokio = {version = "1.38.0", features = ["rt-multi-thread"]}

# OCI container specs.
oci-spec = { version = "0.6.8", features = ["runtime"] }

# Kata Agent protocol.
protocols = { path = "../../libs/protocols", features = ["with-serde"] }
protobuf = "3.2.0"

# dm-verity root hash support
generic-array = "0.14.6"
sha2 = "0.10.6"
tarindex = { git = "https://github.com/kata-containers/tardev-snapshotter", rev = "06183a5" }
tempfile = "3.5.0"
zerocopy = "0.6.1"
fs2 = "0.4.3"

# containerd image pull support
k8s-cri = "0.7.0"
tonic = "0.9.2"
tower = "0.4.13"
containerd-client = "0.4.0"

# username to UID:GID mapping support
tar = "0.4.41"

[dev-dependencies]
kata-agent-policy = { path = "../../agent/policy" }
slog = "2.5.2"
