[package]
name = "genpolicy"
version = "0.1.0"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2021"

[dependencies]
# Logging.
env_logger = "0.10.0"
log = "0.4.17"

# Command line parsing.
clap = { version = "4.1.8", features = ["derive"] }

# YAML file serialization/deserialization.
base64 = "0.21.0"
serde = { version = "1.0.159", features = ["derive"] }

# Newer serde_yaml versions are using unsafe-libyaml instead of yaml-rust,
# and incorrectly change on serialization:
#
# value: "yes"
#
# to:
#
# value: yes
#
# In YAML, the value yes without quotes is reserved for boolean,
# and confuses kubectl, that expects a string value.
serde_yaml = "0.8"

# Container repository.
anyhow = "1.0.32"
async-trait = "0.1.68"
docker_credential = "1.2.0"
flate2 = { version = "1.0.26", features = ["zlib-ng"], default-features = false }
oci-distribution = { version = "0.9.4" }
openssl = { version = "0.10.54", features = ["vendored"] }
serde_ignored = "0.1.7"
serde_json = "1.0.39"
serde-transcode = "1.1.1"
tokio = {version = "1.33.0", features = ["rt-multi-thread"]}

# OCI container specs.
oci = { path = "../../libs/oci" }

# Kata Agent prototol.
protocols = { path = "../../libs/protocols", features = ["with-serde"] }
protobuf = "3.2.0"

# dm-verity root hash support
generic-array = "0.14.6"
sha2 = "0.10.6"
tarindex = { path = "../../tardev-snapshotter/tarindex" }
tempfile = "3.5.0"
zerocopy = "0.6.1"
