# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[workspace]
resolver = "2"

[package]
name = "kata-ctl"
version = "0.0.1"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
clap = { version = "4.1.13", features = ["derive", "cargo"] }
serde_json = "1.0.85"
thiserror = "1.0.35"
privdrop = "0.5.2"
nix = "0.25.0"
strum = "0.24.1"
strum_macros = "0.24.3"
serde = { version = "1.0.149", features = ["derive"] }
url = "2.3.1"
futures = "0.3.24"
base64 = "0.13.0"
toml = "0.5.8"
sys-info = "0.9.1"

shim-interface = { path = "../../libs/shim-interface"}
kata-types = { path = "../../libs/kata-types" }
kata-sys-util = { path = "../../../src/libs/kata-sys-util/" }
safe-path = { path = "../../libs/safe-path" }
agent = { path = "../../runtime-rs/crates/agent"}
serial_test = "0.5.1"
vmm-sys-util = "0.11.0"
epoll = "4.0.1"
libc = "0.2.138"

# Note: this crate sets the slog 'max_*' features which allows the log level
# to be modified at runtime.
logging = { path = "../../libs/logging" }
slog = "2.7.0"
slog-scope = "4.4.0"
hyper = "0.14.20"
tokio = { version = "1.28.1", features = ["signal"] }
ttrpc = "0.8.4"

prometheus = { version = "0.13.0", features = ["process"] }
procfs = "0.12.0"
lazy_static = "1.2"

# for log-parser
serde_yaml = "0.9"
ron = "0.8"
quick-xml = { version = "0.28", features = ["serialize"]}
csv = "1.2"
serde_with = "2.3"
chrono = { version = "0.4", features = ["serde"]}

[target.'cfg(target_arch = "s390x")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "native-tls"] }

[target.'cfg(not(target_arch = "s390x"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "rustls-tls"] }

[dev-dependencies]
semver = "1.0.12"
tempfile = "3.1.0"
nix = "0.25.0"
test-utils = { path = "../../libs/test-utils" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", branch = "main" }
