name: CI | Publish CC runtime payload for amd64
on:
  workflow_call:
    inputs:
      target-arch:
        required: true
        type: string

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        measured_rootfs:
          - no
        asset:
          - cloud-hypervisor
          - qemu
          - virtiofsd
          - kernel-sev
          - ovmf-sev
          - ovmf
          - qemu-snp-experimental
          - qemu-tdx-experimental
          - rootfs-initrd-sev
          - cc-tdx-td-shim
          - tdvf
        include:
          - measured_rootfs: yes
            asset: kernel
          - measured_rootfs: yes
            asset: kernel-tdx-experimental
          - measured_rootfs: yes
            asset: cc-rootfs-image
          - measured_rootfs: yes
            asset: rootfs-image-tdx
    steps:
      - name: Login to Kata Containers quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This is needed in order to keep the commit ids history
      - name: Build ${{ matrix.asset }}
        run: |
          USE_CACHE="no" make "${KATA_ASSET}-tarball"
          build_dir=$(readlink -f build)
          # store-artifact does not work with symlink
          sudo cp -r "${build_dir}" "kata-build"
        env:
          KATA_ASSET: ${{ matrix.asset }}
          TAR_OUTPUT: ${{ matrix.asset }}.tar.gz
          PUSH_TO_REGISTRY: yes
          MEASURED_ROOTFS: ${{ matrix.measured_rootfs }}

      - name: store-artifact ${{ matrix.asset }}
        uses: actions/upload-artifact@v3
        with:
          name: kata-artifacts
          path: kata-build/kata-static-${{ matrix.asset }}.tar.xz
          retention-days: 1
          if-no-files-found: error

      - name: store-artifact root_hash_tdx.txt 
        uses: actions/upload-artifact@v3
        with:
          name: root_hash_tdx.txt
          path: tools/osbuilder/root_hash_tdx.txt
          retention-days: 1
          if-no-files-found: ignore

      - name: store-artifact root_hash_vanilla.txt 
        uses: actions/upload-artifact@v3
        with:
          name: root_hash_vanilla.txt
          path: tools/osbuilder/root_hash_vanilla.txt
          retention-days: 1
          if-no-files-found: ignore

  build-asset-cc-shim-v2:
    runs-on: ubuntu-latest
    needs: build-asset
    steps:
      - name: Login to Kata Containers quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Get root_hash_tdx.txt
        uses: actions/download-artifact@v3
        with:
          name: root_hash_tdx.txt
          path: tools/osbuilder/

      - name: Get root_hash_vanilla.txt
        uses: actions/download-artifact@v3
        with:
          name: root_hash_vanilla.txt
          path: tools/osbuilder/

      - name: Build cc-shim-v2
        run: |
          USE_CACHE="no" make cc-shim-v2-tarball
          build_dir=$(readlink -f build)
          # store-artifact does not work with symlink
          sudo cp -r "${build_dir}" "kata-build"
        env:
          PUSH_TO_REGISTRY: yes
          MEASURED_ROOTFS: yes

      - name: store-artifact cc-shim-v2
        uses: actions/upload-artifact@v3
        with:
          name: kata-artifacts
          path: kata-build/kata-static-cc-shim-v2.tar.xz
          retention-days: 1
          if-no-files-found: error

  create-kata-tarball:
    runs-on: ubuntu-latest
    needs: [build-asset, build-asset-cc-shim-v2]
    steps:
      - uses: actions/checkout@v3
      - name: get-artifacts
        uses: actions/download-artifact@v3
        with:
          name: kata-artifacts
          path: kata-artifacts
      - name: merge-artifacts
        run: |
          ./tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh kata-artifacts
      - name: store-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kata-static-tarball
          path: kata-static.tar.xz
          retention-days: 1
          if-no-files-found: error

  kata-payload:
    needs: create-kata-tarball
    runs-on: ubuntu-latest
    steps:
      - name: Login to Confidential Containers quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.COCO_QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.COCO_QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v3
      - name: get-kata-tarball
        uses: actions/download-artifact@v3
        with:
          name: kata-static-tarball

      - name: build-and-push-kata-payload
        id: build-and-push-kata-payload
        run: |
          ./tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh \
          $(pwd)/kata-static.tar.xz "quay.io/confidential-containers/runtime-payload-ci" \
          "kata-containers-${{ inputs.target-arch }}"
