name: Kata Containers CI
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] See #11332.
    branches:
      - 'main'
    types:
      # Adding 'labeled' to the list of activity types that trigger this event
      # (default: opened, synchronize, reopened) so that we can run this
      # workflow when the 'ok-to-test' label is added.
      # Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
      - opened
      - synchronize
      - reopened
      - labeled

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  skipper:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/gatekeeper-skipper.yaml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      target-branch: ${{ github.event.pull_request.base.ref }}

  # kata-containers-ci-on-push:
  #   needs: skipper
  #   if: ${{ needs.skipper.outputs.skip_build != 'yes' }}
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write
  #     attestations: write
  #   uses: ./.github/workflows/ci.yaml
  #   with:
  #     commit-hash: ${{ github.event.pull_request.head.sha }}
  #     pr-number: ${{ github.event.pull_request.number }}
  #     tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
  #     target-branch: ${{ github.event.pull_request.base.ref }}
  #     skip-test: ${{ needs.skipper.outputs.skip_test }}
  #   secrets:
  #     AUTHENTICATED_IMAGE_PASSWORD: ${{ secrets.AUTHENTICATED_IMAGE_PASSWORD }}
  #     AZ_APPID: ${{ secrets.AZ_APPID }}
  #     AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  #     AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  #     CI_HKD_PATH: ${{ secrets.CI_HKD_PATH }}
  #     ITA_KEY: ${{ secrets.ITA_KEY }}
  #     QUAY_DEPLOYER_PASSWORD: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}
  #     NGC_API_KEY: ${{ secrets.NGC_API_KEY }}
  #     KBUILD_SIGN_PIN: ${{ secrets.KBUILD_SIGN_PIN }}
