name: Kata Containers CI
on:
  pull_request_target:
    branches:
      - 'main'

jobs:
  build-kata-static-tarball-amd64:
    uses: ./.github/workflows/build-kata-static-tarball-amd64.yaml
    with:
      tarball-suffix: -${{ github.event.pull_request.number}}-${{ github.event.pull_request.head.sha }}

  publish-kata-deploy-payload-amd64:
    needs: build-kata-static-tarball-amd64
    uses: ./.github/workflows/publish-kata-deploy-payload-amd64.yaml
    with:
      tarball-suffix: -${{ github.event.pull_request.number}}-${{ github.event.pull_request.head.sha }}
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}-amd64
    secrets: inherit

  run-k8s-tests-on-aks:
    needs: publish-kata-deploy-payload-amd64
    uses: ./.github/workflows/run-k8s-tests-on-aks.yaml
    with:
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}-amd64
    secrets: inherit

  run-k8s-tests-on-sev:
    needs: publish-kata-deploy-payload-amd64
    uses: ./.github/workflows/run-k8s-tests-on-sev.yaml
    with:
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}-amd64

  run-k8s-tests-on-snp:
    needs: publish-kata-deploy-payload-amd64
    uses: ./.github/workflows/run-k8s-tests-on-snp.yaml
    with:
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}-amd64

  run-k8s-tests-on-tdx:
    needs: publish-kata-deploy-payload-amd64
    uses: ./.github/workflows/run-k8s-tests-on-tdx.yaml
    with:
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}-amd64

  run-metrics-tests:
    needs: build-kata-static-tarball-amd64
    uses: ./.github/workflows/run-launchtimes-metrics.yaml
