name: CI | Create AKS cluster
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log into the Azure account
        run: |
          az login \
            --service-principal \
            -u "${{ secrets.AZ_APPID }}" \
            -p "${{ secrets.AZ_PASSWORD }}" \
            --tenant "${{ secrets.AZ_TENANT_ID }}"

      - name: Create AKS cluster
        run: |
          az aks create \
            -g "kataCI" \
            -n "${{ inputs.name }}" \
            -s "Standard_D4s_v5" \
            --node-count 1 \
            --generate-ssh-keys
