# When a release page is published, start the release artifact process
on:
 push:
  tags:
  - '*'
name: Build, Test, and Publish kata-deploy

jobs:
  # create image and upload to release page (can we get branch information from release tag?
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name : the ok ok 
      run: |  
        echo "hello worold"
        #sudo apt-get update
        #sudo apt-get install -y curl git
        echo "still?"
        # for test development:
        git clone https://github.com/egernst/packaging-1
        cd packaging-1/release

        tag=`echo $GITHUB_REF | cut -d/ -f3-`
        echo `pwd`
        echo `ls`

        ./build-artifacts.sh $GITHUB_REF

        echo "done...."
