# When a release page is published, start the release artifact process
on: push.tag
name: Build, Test, and Publish kata-deploy

jobs:
  # create image and upload to release page (can we get branch information from release tag?
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name : the ok ok 
      run: |  
        echo "hello worold"
        sudo apt-get update
        sudo apt-get install -y curl git
        echo "still?"
        # for test development:
        git clone https://github.com/egernst/packaging-1
        cd packaging-1
        echo `pwd`
        echo `ls`
        cd release
        echo `pwd`
        echo `ls`

        #./build-artifacts $GITHUB_TAG
        echo "github tag" $GITHUB_TAG
        echo "github sha" 
        echo $GITHUB_SHA

        echo "done...."

        #        docker run alpine sh -c date
        #        cd obs-packaging
        #        
        #./gen_versions_txt.sh "stable-1.8"
        #        cd ../release
        #        ./publish-kata-image.sh "1.8.2"
        #        ./kata-deploy-binaries.sh "1.8.2"
