on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  kata-deploy-runtime-classes-check:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ensure the split out runtime classes match the all-in-one file
      run: |
        pushd tools/packaging/kata-deploy/runtimeclasses/
        echo "::group::Combine runtime classes"
        for runtimeClass in $(find . -type f \( -name "*.yaml" -and -not -name "kata-runtimeClasses.yaml" \) | sort); do
            echo "Adding ${runtimeClass} to the resultingRuntimeClasses.yaml"
            cat "${runtimeClass}" >> resultingRuntimeClasses.yaml;
        done
        echo "::endgroup::"
        echo "::group::Displaying the content of resultingRuntimeClasses.yaml"
        cat resultingRuntimeClasses.yaml
        echo "::endgroup::"
        echo ""
        echo "::group::Displaying the content of kata-runtimeClasses.yaml"
        cat kata-runtimeClasses.yaml
        echo "::endgroup::"
        echo ""
        diff resultingRuntimeClasses.yaml kata-runtimeClasses.yaml
