# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * 0'
  push:
    branches: [ "main" ]

permissions: {}

jobs:
  scan-scheduled:
    name: Scan of whole repo
    permissions:
      actions: read # # Required to upload SARIF file to CodeQL
      contents: read  # Read commit contents
      security-events: write  # Require writing security events to upload SARIF file to security tab
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8ae4be80636b94886b3c271caad730985ce0611c" # v2.3.3
    with:
      scan-args: |-
        -r
        ./
  scan-pr:
    name: Scan of just PR code
    permissions:
      actions: read # Required to upload SARIF file to CodeQL
      contents: read  # Read commit contents
      security-events: write  # Require writing security events to upload SARIF file to security tab
    if: ${{ github.event_name == 'pull_request' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@b8ae4be80636b94886b3c271caad730985ce0611c" # v2.3.3
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        ./
