name: 'Automatically close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: action/stale@v8
        with:
          start-date: '2023-05-01T00:00:00Z'
          stale-pr-message: 'This PR has been opened without with no activity for 180 days. Comment on the issue otherwise it will be closed in 7 days'
          days-before-pr-stale: 180
          days-before-pr-close: 7
          days-before-issue-stale: -1
          days-before-issue-close: -1
