on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled # a workflow runs only when the 'ok-to-test' label is added

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Static checks self-hosted
jobs:
  skipper:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/gatekeeper-skipper.yaml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      target-branch: ${{ github.event.pull_request.base.ref }}

  build-checks:
    needs: skipper
    if: ${{ needs.skipper.outputs.skip_static != 'yes' }}
    strategy:
      fail-fast: false
      matrix:
        instance:
          - "ubuntu-22.04-arm"
          - "s390x"
          - "ppc64le"
    uses: ./.github/workflows/build-checks.yaml
    with:
      instance: ${{ matrix.instance }}
